### ISSUE TITLE
FreeCAD day at FOSDEM 2023

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#22]
# <img src="https://raw.githubusercontent.com/FreeCAD/FPA/main/images/freecad.svg" style="height:24px;" /> FreeCAD event @ FOSDEM 2023

**Purpose**: Organise a FreeCAD event day, as a side event to FOSDEM 2023

[FOSDEM](https://fosdem.org) is a well-known FOSS developers meeting, held once a year in Brussels, Belgium. It attracts developers from the whole world for a week-end in Brussels. The even is packed with talks, workshops, and is a great place to meet other developers. Many projects use FOSDEM as an opportunity for their developers to meet physically.

The whole FOSDEM is also free to attend and open to anybody, no booking required. It usually brings a lot of people from around Brussels.

FreeCAD develpers Yorik, Sliptonic, KKremitzki, vejmarie already met at FOSDEM 2019, it was a great experience and led to many new ideas. We would like to do it again and interest more FreeCAD developers and community members to join.

FOSDEM itself happens on **4th and 5th february 2023**. We propose to make the FreeCAD event on **friday february 3rd, 2023**, so folks can participate to the FreeCAD day and still enjoy the rest of FOSDEM.

### Before the FreeCAD day

For who has already arrived in Brussels, we could meet on thursday night in a cool place with food and drink to meet up, share some  stories. It could be just a food bar or a fuller belgian experience such as a typical restaurant. It will be at [t'Kelderke](https://restaurant-het-kelderke.be/en) from 19h

### FreeCAD day

We will look for suitable locations, one good location would be the [Brussels hackerspace](https://hsbxl.be/), but I (Yorik) am not sure it will be available as it uses to host a Debian event during FOSDEM. Otherwise FOSDEM itself might help us to find a space.

The event could be formatted as an [unconference](https://en.wikipedia.org/wiki/Unconference) and what happens in it be decided by the participants on the day of the event. However, since not everybody will be able to attend, it might be useful to prepare time slots that can be filled in advance too.

 Anybody is free to propose an activity to fill the time slots:

#### Thursday February 2nd, 2023

| Time  | Proponent | Activity                                                                                                                                 |
| ----- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------- |
| 18:00  | @yorikvanhavre  | Meet for a drink/food in a nice place in Brussels (ex. [le Cirio](https://lecirio.be/en))                                                            |

#### Friday February 3rd, 2023

| Time  | Proponent | Activity                                                                                                                                 |
| ----- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------- |
| 9:00  | @yorikvanhavre  | Welcome to the FreeCAD day, informal meeting, who is who, and have a coffee                                                              |
| 10:00 |  |                                                                                                                                       |
| 11:00 |           |                                                                                                                                          |
| 12:00 |           |                                                                                                                                          |
| 13:00 |           |                                                                                                                                          |
| 14:00 |           |                                                                                                                                          |
| 15:00 |           |                                                                                                                                          |
| 16:00 |           |                                                                                                                                          |
| 17:00 |           |                                                                                                                                          |
| 18:00 | FOSDEM    | Traditionally, FOSDEM organizes a beer night on friday evening. We might all want to go there grab a beer or something. FOSDEM still did not publish the details.

#### Saturday and Sunday February 4th and 5th, 2023

FOSDEM, no specific FreeCAD activities scheduled, but FreeCAD community members are welcome to meet/gather around

**Recording** Should there be talks recorded for others to see? How?

### FOSDEM talks

FOSDEM itself will feature an **open CAD/CAM/hardware devroom**, where FreeCAD-related talks can be proposed (the proposal period is between november 5th and december 15th). We also encourage FreeCAD community members to propose FreeCAD-related talks there.

### FOSDEM booth

Finally, FOSDEM offers to [have a boot/stand](https://fosdem.org/2023/news/2022-09-26-stands-cfp/) in the main lobby. If there is enough interest and volunteers to maintain it. We could also print some t-shirts and stickers to sell and give there.

### Tasks to be done (add yours and add your name if you wish to help with any)

* [x] Announce travel grants
* [x] Find a place to do the meeting ( @yorikvanhavre ) - Hackerspace Brussels likely occupied that day by Debian hackaton. Found and booked at [Ateliers des tanneurs](https://www.ateliersdestanneurs.be/en/salles/salle-3/#&gid=1&pid=1)
* [x] Organize food/coffee for the meeting ( @yorikvanhavre ) - Available from the Tanneur's own food provider at 9€/person - Need an estimate of the number of persons attending
* [x] Print t-shirts?
* [x] Print stickers?
* [ ] ~~Print pencils?~~ cancelled
* [ ] ~~3D-print key hangers?~~ cancelled
* [x] Print poster to be put at the event day
* [x] Enquire about having a FreeCAD stand/booth at FOSDEM ( @yorikvanhavre ) - Too late, but Open Toolchain foundation has one and propses to share with us. Needs volunteers!
* [x] Find & organize a restaurant for thursday evening ( @yorikvanhavre ) - at t'kelderke on thursday 02/02, at 19h - https://restaurant-het-kelderke.be/en
* [x] Create a chat room (matrix, telegram, forum?) for attendees to meet and schedule
* [x] Create a list of confirmed attendees to estimate food, t-shirts, thurday night booking...

**Comment by goatchurchprime** [comment]
We can make up the timetable on the day depending on who is there, and have a show of hands if there is a clash or too many.

I'll do:

* Problems and solutions with the internal NC code format when making easy post-processors (10 minutes)

@trilbytim can do:
* Losing the inheritance tree and making multiple areas from one sketch drawing (like OnShape), with reference to real examples of a kitchen rudder and a hang-glider airframe.  (30 minutes)

**Comment by chennes** [comment]
I'd love to have a discussion about the Addon Manager, and how we can continue to improve its user experience.

**Comment by yorikvanhavre** [comment]
Travel grants are available: https://blog.freecad.org/2022/11/16/fosdem-and-freecad-meeting-travel-grants/

**Comment by yorikvanhavre** [comment]
Devs that have confirmed presense so far:
@yorikvanhavre 
@chennes 
@sliptonic 
@AjinkyaDahale
@KeithSloan

**Comment by yorikvanhavre** [comment]
Resume of spendings engaged/foreseen so far:
* Hiring of the room at Atelier des Tanneurs: 390 € (booked, not yet paid)
* Coffee/snacks at Atelier des Tanneurs: 9€ / person, estimating 20 people = 180 €
* Printing of stickers: 47.55 €
* Printing of 25 t-shirts: 250 €
Total: 867.55 € (of which we should get 250 back as people would pay for their own t-shirts)
* Possible participation in Thursday evening restaurant costs, ex. 20€ / person x 10 = 200 €

**Comment by timmwille** [comment]
I will also join with colleagues and friends from the opentoolchain.org, if it fits we can do a little intro there as well. I'm really looking forward to meet you.

**Comment by papamat** [comment]
Hello people, I can't wait to meet all of you there. We can have a slot, or even half slot if there are many presenters, to talk about how we in Libre Space Foundation, use FreeCAD to built stuff that are going to space.

**Comment by yorikvanhavre** [comment]
The thursday night evente for who's already there, will be at t'Kelderke - https://restaurant-het-kelderke.be/en i'll be there at 19h. Please reach to me if you're going to be there, so i can book a table acoordingly!

**Comment by timmwille** [comment]
Is there now a final FreeCAD Day location? is it https://www.ateliersdestanneurs.be/en/salles/salle-3/#&gid=1&pid=1 ?


In general I would like to propose a slot with introduction to the Open Toolchain Foundation and its first official Dev Funding surrounding FreeCAD if that works for you?

**Comment by yorikvanhavre** [comment]
Tasks left to be done:

* [x] Write a blog post
* [ ] Gather pictures of the event
* [ ] Cut, format and publish video interviews
* [ ] Gather and publish the list of topics discussed during that day
* [ ] Finish accounting

**Comment by yorikvanhavre** [comment]
List of topics that have been discussed:

* Welcome, by yorik
* Addon manager, by chennes
* CAE conference March, by keith sloan
* OS+I automated documentation by Pieter (opentoolchain)
* Docs after wiki? by chennes
* Complaint session by kliment (KiCAD)
* PostCAD by kkremitzki
* Sheet metal, fabrics and gliders by julian todd
* Thermal modeling by ?? (I don't remember their name?)
* What is a maintainer by chennes
* OpenToolchain foundation by opentoolchain team
* OpenSCAD enhancement by keith sloan
* Organizing toponaming update by john dupuy (ondsel)
* FPA funding ideas by yorik

**Comment by KeithSloan** [comment]
Thermal modelling was I think by wookey

**Comment by chennes** [comment]
My event write-up and notes (plus continuing discussion) can be found on the Forums at https://forum.freecad.org/viewtopic.php?t=75768

**Comment by yorikvanhavre** [comment]
Costs breakdown:
* Room: 390€ + 21%VAT = 471.90€ - fully paid
* Food: 9*25 = 225€ + 21%VAT = 272,25€ - awaiting bill
* Stickers: 47.55 € - paid by Yorik, will do a request on opencollective
* T-shirts: 354.35€ + 21€VAT = 428.76€ for 30 t-shirts = 14.30 each. 15 paid @ 15€ = 225€, rest 428.76 - 225 = 204.76 € - paid by Yorik, will do a request on opencollective
* Thursday night restaurant: 405.40€ subject to approval by FPA
Total without restaurant: 996.46€

**Comment by yorikvanhavre** [comment]
Pictures taken by @timmwille 

![photo1675643282](https://user-images.githubusercontent.com/1136856/218702825-cd3d69be-5b2a-42af-ba36-50a2cdd28c75.jpeg)
![photo1675643280(1)](https://user-images.githubusercontent.com/1136856/218702834-f6b04c3d-efaa-445c-9e4e-eb1f3769fa3e.jpeg)
![photo1675643280](https://user-images.githubusercontent.com/1136856/218702836-bdb751d2-ef20-49d8-9be4-164203d251c2.jpeg)
![photo1675643279(1)](https://user-images.githubusercontent.com/1136856/218702840-78a1893b-9024-46cd-9b84-efde94f67480.jpeg)
![photo1675643279](https://user-images.githubusercontent.com/1136856/218702846-c0c796d8-a0ea-4667-a30e-19bb169b19de.jpeg)
![photo1675643278(1)](https://user-images.githubusercontent.com/1136856/218702849-d7996782-1b86-4410-b66b-d4f9bf05d80c.jpeg)
![photo1675643278](https://user-images.githubusercontent.com/1136856/218702852-b5093fa3-b274-4620-b25f-97c309c78ab7.jpeg)
![photo1675643277(1)](https://user-images.githubusercontent.com/1136856/218702855-4f23ba02-4ac8-4a55-9cef-e57513097f47.jpeg)
![photo1675643277](https://user-images.githubusercontent.com/1136856/218702857-d66df2f5-2574-4919-8e40-9614d3c7ac60.jpeg)
![photo1675643276](https://user-images.githubusercontent.com/1136856/218702860-ed7a03cd-2737-4921-82f4-e1ed07858edf.jpeg)

**Comment by yorikvanhavre** [comment]
Pictures taken by me

![2023-02-02 11 43 18](https://user-images.githubusercontent.com/1136856/218712035-1894b51c-5727-4aec-8063-d596c4f2c7fc.jpg)
![2023-02-02 16 49 10](https://user-images.githubusercontent.com/1136856/218712041-61dcbd3b-7c47-436a-95fb-a389c7478485.jpg)
![2023-02-03 09 24 50](https://user-images.githubusercontent.com/1136856/218712046-42ed7000-d1ca-4801-b489-13651683b731.jpg)
![2023-02-03 09 25 03](https://user-images.githubusercontent.com/1136856/218712049-a40b90db-45a7-4eae-a863-a224db907b52.jpg)
![2023-02-03 09 59 24](https://user-images.githubusercontent.com/1136856/218712051-73d55592-cefb-468f-8cb4-06533d3f8fc5.jpg)
![2023-02-03 09 59 42](https://user-images.githubusercontent.com/1136856/218712057-e979e107-723e-4d9c-837e-739545cc9ba4.jpg)
![2023-02-03 10 47 08](https://user-images.githubusercontent.com/1136856/218712060-c919127b-6ff4-4c5b-8a8d-f5bd296f8d4f.jpg)
![2023-02-03 11 15 23](https://user-images.githubusercontent.com/1136856/218712065-7a11b5bc-7765-4a07-afbc-eae908487335.jpg)
![2023-02-03 11 42 14](https://user-images.githubusercontent.com/1136856/218712068-b09a5d6f-85a9-497e-b161-b53cc1e1856f.jpg)
![2023-02-03 12 07 58](https://user-images.githubusercontent.com/1136856/218712072-ec708d94-fccf-4403-ae79-0b65b2a71ce2.jpg)
![2023-02-03 12 08 04](https://user-images.githubusercontent.com/1136856/218712077-883b0d52-0f8e-4308-a113-88938fa354e1.jpg)
![2023-02-03 12 08 10](https://user-images.githubusercontent.com/1136856/218712078-ae6b4f2e-e29c-4232-b6a5-22b6306eef48.jpg)
![2023-02-03 12 08 19](https://user-images.githubusercontent.com/1136856/218712081-1cca629e-d1d7-4c67-8289-14a0e58f56f4.jpg)
![2023-02-03 12 42 46](https://user-images.githubusercontent.com/1136856/218712085-b76f5f05-4ad1-4ed8-ac22-167745ccb892.jpg)
![2023-02-03 12 44 03](https://user-images.githubusercontent.com/1136856/218712088-c4c638c2-778c-48ab-a2cc-01ffe37c636f.jpg)
![2023-02-03 13 10 10](https://user-images.githubusercontent.com/1136856/218712091-653f67ba-ac16-4f3b-bce3-0e7d9357aaf8.jpg)
![2023-02-03 14 13 40](https://user-images.githubusercontent.com/1136856/218712097-b3aba684-46ec-429a-9e5a-267e90481cad.jpg)
![2023-02-03 14 35 32](https://user-images.githubusercontent.com/1136856/218712099-0fe9df2b-fa1c-4762-9ff6-cc82df7c2768.jpg)
![2023-02-03 14 38 39](https://user-images.githubusercontent.com/1136856/218712101-41d7c5e7-87e5-4af4-8f34-51e68360ed67.jpg)
![2023-02-03 15 05 25](https://user-images.githubusercontent.com/1136856/218712106-45992016-842d-42a4-9c3c-2a730ffa752a.jpg)
![2023-02-03 16 00 00](https://user-images.githubusercontent.com/1136856/218712108-d634a93e-904b-47f0-ada2-3920abb15c45.jpg)
![2023-02-03 16 30 03](https://user-images.githubusercontent.com/1136856/218712114-cdcdc9f8-c2e1-4102-b9fe-d6398f5b40ed.jpg)
![2023-02-03 21 47 19](https://user-images.githubusercontent.com/1136856/218712115-40f3ad3b-db52-445f-923a-7d8b3170e091.jpg)
![2023-02-03 21 47 32](https://user-images.githubusercontent.com/1136856/218712116-62da43c5-485e-4712-9c56-a7af29eab152.jpg)
![2023-02-03 21 47 44](https://user-images.githubusercontent.com/1136856/218712118-7a699b8f-9af8-4f70-a9a9-0cb95d0e12d4.jpg)

**Comment by yorikvanhavre** [comment]
![photo1675614410](https://user-images.githubusercontent.com/1136856/219075267-05e85ef0-0b35-422a-be79-0b93675ccbd1.jpeg)
